version: "3.4"

networks:
  net:
    driver: overlay
    attachable: true
  infra_traefik:
    external: true
  elasticsearch_esnetwork:
    external: true


volumes:
  prometheus: {}
  grafana: {}
  alertmanager: {}
  fbsock:
    name: prometheus.${STACKDOMAIN:-loc.alho.st}_fbsock


configs:
  dockerd_config:
    file: ./dockerd-exporter/Caddyfile
  node_rules:
    file: ./prometheus/rules/swarm_node.rules.yml
  task_rules:
    file: ./prometheus/rules/swarm_task.rules.yml
  fbconfig:
     file: ./fluent-bit.conf


services:
  fluentbit:
    image: fluent/fluent-bit:latest
    command: /fluent-bit/bin/fluent-bit -v -c /fluent-bit/etc/fluent-bit.conf
    configs:
      - source: fbconfig
        target: /fluent-bit/etc/fluent-bit.conf
      #- source: fbparsers
      #  target: /fluent-bit/etc/parsers-test.conf
    deploy:
      mode: global
    networks:
      elasticsearch_esnetwork:
    volumes:
      - fbsock:/fbsock/
      #- thredds_logs:/thredds-logs/

  dockerd-exporter:
    image: stefanprodan/dockerd-exporter
    networks:
      - net
    environment:
      - DOCKER_GWBRIDGE_IP=172.18.0.1
    configs:
      - source: dockerd_config
        target: /etc/caddy/Caddyfile
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  cadvisor:
    image: google/cadvisor
    networks:
      - net
    command: -logtostderr -docker_only
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  grafana:
    image: stefanprodan/swarmprom-grafana:5.0.1
    networks:
      - net
      - infra_traefik
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-test}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-ThisTest3d}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=https://admin.${STACKDOMAIN:-loc.alho.st}/grafana/
      #- GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL:-localhost}
      #- GF_SMTP_ENABLED=${GF_SMTP_ENABLED:-false}
      #- GF_SMTP_FROM_ADDRESS=${GF_SMTP_FROM_ADDRESS:-grafana@test.com}
      #- GF_SMTP_FROM_NAME=${GF_SMTP_FROM_NAME:-Grafana}
      #- GF_SMTP_HOST=${GF_SMTP_HOST:-smtp:25}
      #- GF_SMTP_USER=${GF_SMTP_USER}
      #- GF_SMTP_PASSWORD=${GF_SMTP_PASSWORD}
    volumes:
      - grafana:/var/lib/grafana
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        traefik.docker.network: infra_traefik
        traefik.grafana.port: 3000
        #traefik.grafana.frontend.rule: Host:graphana.${STACKDOMAIN:-loc.alho.st}
        #traefik.grafana.frontend.rule: PathPrefixStrip:/grafana/
        traefik.grafana.frontend.rule: Host:admin.${STACKDOMAIN:-loc.alho.st};PathPrefixStrip:/grafana/
        # user: test, password: ThisTest3d
        #traefik.frontend.auth.basic: test:$$2y$$05$$eW9/S3Ay8LD0GrTZvQA/guIAhwVlZPHcEngteXmy0A1YSCN4V3Rpq
    logging:
      driver: "fluentd"
      options:
        tag: infra.monitoring


  alertmanager:
    image: stefanprodan/swarmprom-alertmanager:v0.14.0
    networks:
      - net
      - infra_traefik
    environment:
      - SLACK_URL=${SLACK_URL:-https://hooks.slack.com/services/TOKEN}
      - SLACK_CHANNEL=${SLACK_CHANNEL:-general}
      - SLACK_USER=${SLACK_USER:-alertmanager}
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    volumes:
      - alertmanager:/alertmanager
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        traefik.docker.network: infra_traefik
        traefik.alertmanager.port: 9093
        #traefik.alertmanager.frontend.rule: Host:port.${STACKDOMAIN:-loc.alho.st}
        traefik.alertmanager.frontend.rule: Host:admin.${STACKDOMAIN:-loc.alho.st};PathPrefixStrip:/alertmanager/
        # user: test, password: ThisTest3d
        traefik.frontend.auth.basic: test:$$2y$$05$$eW9/S3Ay8LD0GrTZvQA/guIAhwVlZPHcEngteXmy0A1YSCN4V3Rpq
    logging:
      driver: "fluentd"
      options:
        tag: infra.monitoring

  unsee:
    image: cloudflare/unsee:v0.8.0
    networks:
      - net
      - infra_traefik
    environment:
      - "ALERTMANAGER_URIS=default:http://alertmanager:9093"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.docker.network: infra_traefik
        traefik.unsee.port: 9094
        traefik.unsee.frontend.rule: Host:admin.${STACKDOMAIN:-loc.alho.st};PathPrefixStrip:/unsee/
        # user: test, password: ThisTest3d
        traefik.frontend.auth.basic: test:$$2y$$05$$eW9/S3Ay8LD0GrTZvQA/guIAhwVlZPHcEngteXmy0A1YSCN4V3Rpq
    logging:
      driver: "fluentd"
      options:
        tag: infra.monitoring

  node-exporter:
    image: stefanprodan/swarmprom-node-exporter:v0.15.2
    networks:
      - net
      - infra_traefik
    environment:
      - NODE_ID={{.Node.ID}}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      # no collectors are explicitely enabled here, because the defaults are just fine,
      # see https://github.com/prometheus/node_exporter
      # disable ipvs collector because it barfs the node-exporter logs full with errors on my centos 7 vm's
      - '--no-collector.ipvs'
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  prometheus:
    image: stefanprodan/swarmprom-prometheus:v2.2.0-rc.0
    networks:
      - net
      - infra_traefik
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=24h'
    environment:
      JOBS: traefik_server:8080
    volumes:
      - prometheus:/prometheus
    configs:
      - source: node_rules
        target: /etc/prometheus/swarm_node.rules.yml
      - source: task_rules
        target: /etc/prometheus/swarm_task.rules.yml
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 128M

